apiVersion: apps/v1
kind: Deployment
metadata:
  name: easybank-app
  namespace: default
  annotations: {}
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: easybank-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: easybank-app
      annotations: {}
    spec:
      containers:
      - name: easybank-app
        image: 217281135028.dkr.ecr.us-west-2.amazonaws.com/easybank-app:latest
        env:
        - name: JAVA_OPTS
          value: -Xms256m -Xmx512m -XX:+UseG1GC -Dspring.profiles.active=production
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15 