spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/easybank
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  mybatis:
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    mapper-locations: classpath*:mapper/AccountRepository.xml
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080

logging:
  level:
    com.example.easybank: DEBUG
    org.springframework.cache: TRACE