apiVersion: apps/v1
kind: Deployment
metadata:
  name: easybank-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: easybank-app
  template:
    metadata:
      labels:
        app: easybank-app
    spec:
      containers:
      - name: easybank-app
        image: easybank-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: easybank-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: easybank-secrets
              key: db-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: easybank-secrets
              key: db-password
        - name: SPRING_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: easybank-config
              key: redis-host
        - name: SPRING_REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: easybank-config
              key: redis-port
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m" 