apiVersion: apps/v1
kind: Deployment
metadata:
  name: easybank-app
  labels:
    app: easybank-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easybank-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: easybank-app
    spec:
      containers:
      - name: easybank-app
        image: 217281135028.dkr.ecr.us-west-2.amazonaws.com/easybank-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "384Mi"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: easybank-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: easybank-secrets
              key: db-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: easybank-secrets
              key: db-password
        - name: SPRING_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: easybank-config
              key: redis-host
        - name: SPRING_REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: easybank-config
              key: redis-port
        - name: JAVA_OPTS
          value: "-Xms128m -Xmx256m -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication -Dspring.profiles.active=production"
        - name: SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE
          value: "3"
        - name: SPRING_DATASOURCE_HIKARI_MINIMUM-IDLE
          value: "1"
        - name: SPRING_DATASOURCE_HIKARI_MAX-LIFETIME
          value: "1800000"
        - name: SPRING_DATASOURCE_HIKARI_IDLE-TIMEOUT
          value: "300000"
        - name: SPRING_REDIS_POOL_MAX-ACTIVE
          value: "5"
        - name: SPRING_REDIS_POOL_MAX-IDLE
          value: "2"
        - name: SPRING_REDIS_POOL_MIN-IDLE
          value: "1"
        - name: MAX_REQUESTS_PER_MINUTE
          value: "300"
        - name: MAX_TRANSACTIONS_PER_MINUTE
          value: "50"
        - name: RETRY_AFTER_SECONDS
          value: "30"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 300
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 240
          timeoutSeconds: 10
          periodSeconds: 20
          failureThreshold: 3
      imagePullSecrets:
      - name: regcred 