apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-proxy-custom
  namespace: kube-system
data:
  config.conf: |
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    kind: KubeProxyConfiguration
    metricsBindAddress: 0.0.0.0:10249
    mode: "iptables"
    conntrack:
      maxPerCore: 8192
      min: 4096
      tcpEstablishedTimeout: 24h0m0s
      tcpCloseWaitTimeout: 1h0m0s
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: kube-proxy
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi 